### ISSUE TITLE
IKnobMultiControlText

### ISSUE THREAD

**Issue by johannesmenzel** [olilarkin/wdl-ol#119]
Hello there,

I'm taking my first steps to DSP programming, so please be patient ;)

I tried to insert controls for parameters with a knob and text box entries. After scanning the web, I found out you always refer to the IKnobMultiControlText class from the MultiTarget example. Since this is not in the standard wdl library, I included the examples header file containing the class. The question would be: Will that class will be included again in the standard library, if not, is it depreciated? What would be the most elegant solution replacing this behavior? Will there be another multi control class? And how does the IRECT of the textbox of this class work? I expected it to be the top left corner of the textbox, but it appeared anywhere else.

P.S. If you see me using concepts wrong, please do correct me, I'm learning.

**Comment by olilarkin** [comment]
just copy the IKnobMultiControlText class to your project. Currently working on iPlug2 where there will be a richer controls library
