### ISSUE TITLE
App (standalone) doesn't build in Xcode 9.4.x on macOS High Sierra

### ISSUE THREAD

**Issue by kyr0** [olilarkin/wdl-ol#123]
If you try to build the App target (standalone) on macOS High Sierra using Xcode 9.4.x, the following will happen: builder (CpResources) will fail to build it, when an `APP_FOLDER` is set in `common.xconfig`. It will somehow concatenate the folder twice, resulting in an odd error:

<img width="853" alt="bildschirmfoto 2018-08-24 um 00 01 01" src="https://user-images.githubusercontent.com/454817/44554403-16a5c980-a731-11e8-80e1-cca75ad34e0e.png">

To improve the situation (I'm unable to fix it completely)

1) Set the APP_FOLDER in `common.xconfig` to: `APP_FOLDER = /`

<img width="430" alt="bildschirmfoto 2018-08-24 um 00 25 59" src="https://user-images.githubusercontent.com/454817/44555190-4f936d80-a734-11e8-89ef-ebee4dfd6894.png">

2) Set "Installation Directory" to "/Applications"

<img width="1151" alt="bildschirmfoto 2018-08-24 um 00 00 03" src="https://user-images.githubusercontent.com/454817/44554448-4f45a300-a731-11e8-9fef-537d25557b17.png">

3) Then, the project will fail with yet another issue:

<img width="580" alt="bildschirmfoto 2018-08-24 um 00 03 42" src="https://user-images.githubusercontent.com/454817/44554473-65536380-a731-11e8-8a72-9ecfae9ddc4a.png">

4) Because the "Build settings" say, the App could be built now, but we wouldn't be able to access it.

<img width="1140" alt="bildschirmfoto 2018-08-24 um 00 17 50" src="https://user-images.githubusercontent.com/454817/44554946-2c1bf300-a733-11e8-9438-2ed94c3cf4c0.png">

So, we need to grant access for ourselves. Change those values to, with _your_ username for sure:

<img width="860" alt="bildschirmfoto 2018-08-24 um 00 19 18" src="https://user-images.githubusercontent.com/454817/44554986-5cfc2800-a733-11e8-8edc-df5c4fad58a8.png">

If you don't know your username, open a Terminal and type `whoami`.

5) You need to let Xcode transform the project structure now. Click here:

<img width="132" alt="bildschirmfoto 2018-08-24 um 00 13 30" src="https://user-images.githubusercontent.com/454817/44554820-c92a5c00-a732-11e8-86c8-e912eec345ec.png">

and select the first file in the list (your project file!). A dialog will appear:

<img width="783" alt="bildschirmfoto 2018-08-24 um 00 14 40" src="https://user-images.githubusercontent.com/454817/44554850-e0694980-a732-11e8-85ad-7ece86b6ec0a.png">

6) Perform all changes.

When you build now, and the warnings are overwhelming, do also transform the Xcode project of "lice" (it is linked in the warnings).

7) FINALLY, after all this journey... 

Still from time to time, the build fails. I need to change the installation folders then.. just randomly switching until it builds again... 

@olilarkin I don't know but after playing like 2h with the issue I can't find a stable solution to fix it

**Comment by olilarkin** [comment]
never seen that before. thanks for the detailed issues, but just a heads up, this code is quite outdated , so don't spend too much energy, since a new thing to test will be public soon

**Comment by kyr0** [comment]
Cool stuff dude :) You don't need to fight alone tho :) In case you would like to get some early feedback, ideas or support with docs, compatibility tests on OS X, code contribution etc., feel free to invite me to your IPlug2 repo.

**Comment by kyr0** [comment]
Hi Oli,

one another thing... I have a novel idea for IPlug2.. it could possibly save you all the work for the GUI... do you have smth. like a slack where we could talk?

Thanks & best,
Aron

**Comment by olilarkin** [comment]
https://join.slack.com/t/iplug-users/shared_invite/enQtNDIyNjk0NDY2ODAwLTk3ZTI0MzNjNDU2ODcwNDk0MzUyMTRmMWU3MTIwMTZhODE0ODdhMGQ4ZDk5MDBmZTlmZTVmNTRiYzQzMDhiNTY

**Comment by olilarkin** [comment]
new version coming soon, hopefully with an updated version of that tutorial. Closing this issue, currently workin on new app wrapper code for iplug2
