### ISSUE TITLE
vst2.4sdk?

### ISSUE THREAD

**Issue by esaruoho** [olilarkin/wdl-ol#127]
how do i find vstsdk2.4 ?

```
put aeffect.h and aeffectx.h from the VST2.4 sdk here

download the vst sdk here:
http://www.steinberg.net/en/company/developer.html

these are the files you need:

/vstsdk2.4/pluginterfaces/vst2.x/aeffect.h
/vstsdk2.4/pluginterfaces/vst2.x/aeffectx.h
```

**Comment by johannesmenzel** [comment]
Vst2 development was dropped by Steinberg in the most recent version. I guess you'd find it in version 3.6.10 and previous ones. You have to deal with the fact that you won't get the permission to publish VST2 plugins anyway:

https://forum.cockos.com/showthread.php?t=212853

**Comment by olilarkin** [comment]
thanks johannes
