### ISSUE TITLE
Double parameters don't automate fractionally in Audiounit version in Logic

### ISSUE THREAD

**Issue by olilarkin** [olilarkin/wdl-ol#20]
In Endless Series I have a parameter "Centre" declared like this

  GP(kCentre)->InitDouble("Centre", 60., 20., 120., 0.01, "st");

In Ableton Live and Presonus Studio One when automating this parameter, it is possible to get fractional values, such as 60.5 and do a smooth interpolation. In Logic however, the automation is quantised to integer steps.

**Comment by madronalabs** [comment]
Pretty sure this is a Logic bug. I see similar results with any AU plugin, though not with Logic's built-in synths.

**Comment by olilarkin** [comment]
Fixed in iplug2
