### ISSUE TITLE
LoadProgramFromFXP extension

### ISSUE THREAD

**Issue by Deisss** [olilarkin/wdl-ol#33]
I'm actually working on preset system, and as I'm away a little from "official" preset system, I found there is no way to load a preset from a given path right now.

This is because the function LoadProgramFromFXP does not handle a path parameter but directly prompt to user a load box... That would be sweet to have a parameter and a prompt only if parameter is empty, something like that...

PS: I can do it if you are out of time, let me know!

**Comment by olilarkin** [comment]
yes the fxp/fxb methods in IPlugBase shouldn't call into GUI methods to prompt and should take a path as an arg instead. I have actually changed this in my "IPlug2" which is not yet public. I will see if I can change it in IPlug1, since I need it for a project too

**Comment by olilarkin** [comment]
modified in ffd01fdedaec8f972bc7e67ee1522afb50ff2f72
