### ISSUE TITLE
Having IControl implementing Observer and Observable design pattern

### ISSUE THREAD

**Issue by Deisss** [olilarkin/wdl-ol#35]
That would be really cool if IControl both implements Observer and Observable pattern.

Currently, if you want to link two graphic object together (let's says a rotary button and a text), you have no choice than sharing paramIdx between both class, and override at least on IsDirty function to check if the value has change or not.

That would be a good improvements to have an Observer pattern and Observable pattern (I can submit base working code for), and then, simply have something:

IButton b1;
IText t1;

t1.registerObserver(b1);
b1.registerObserver(t1);

Then, t1 updates it's mValue when b1 change it's mValue, and then opposite, way more cool and flexible in this way.

As usual, if needed I can try to handle this changes ;)

**Comment by olilarkin** [comment]
i tend just to make one custom IControl rather than linking two IControls

**Comment by Deisss** [comment]
Hum, no way to do that so ? Or should I keep it for myself ?

**Comment by olilarkin** [comment]
i don't have time or inclination to do something like that now, but if you do a nice implementation and pull request i might merge it.

**Comment by Deisss** [comment]
on next or master branch ?

**Comment by olilarkin** [comment]
they are currently even, if i merge i will do it to next though

**Comment by olilarkin** [comment]
If you want to do appeal request for something like this on the iPlugquake branch I will consider it. Closing this issue for now
