### ISSUE TITLE
LICE Build Broken With Xcode 6.3.2

### ISSUE THREAD

**Issue by jonathonracz** [olilarkin/wdl-ol#37]
None of the sample projects compile under the newest Xcode, version 6.3.2. This is from a totally clean pull from GitHub and the 10.5 SDK. Up until this update all was working fine.

The compile errors come from LICE. I'm far from an expert when it comes to Mac development, but I'd guess it has to do with changes to Clang or something.

![screen shot 2015-05-25 at 11 51 35 pm](https://cloud.githubusercontent.com/assets/6502300/7805001/05fe6cb2-0339-11e5-92b5-7c7b5cf1099f.png)

**Comment by olilarkin** [comment]
I just compiled successfully on a fresh 10.10 machine with the same setup you describe. did you let Xcode upgrade the lice project by any chance? Sometimes that can break stuff ;-)

**Comment by jonathonracz** [comment]
Re: upgrading the lice project, no. I'll try doing an Xcode reinstall and report back.

**Comment by jonathonracz** [comment]
Tried downgrading to Xcode 6.3.1 and had the same issue, turns out my aging copy of the OS X 10.5 SDK got corrupted somewhere along the way and that was causing the problem. Hopefully this thread helps someone in the future. Thanks Oli!

**Comment by olilarkin** [comment]
glad you got it sorted!
