### ISSUE TITLE
Wrong plugin recognition in different DAWs

### ISSUE THREAD

**Issue by kbiakov** [olilarkin/wdl-ol#42]
Faced with the following problem. I added the following line to file resource.h:
#define PLUG_CHANNEL_IO "0-1 0-2"

Thus, audioplagin has no audio inputs and has either one (mono) or a pair of (stereo) audio outputs. Cockos REAPER recognize the plugin as VST instrument, but FL Studio see this as VST effect, not instrument. The project compiles into VST2 format in VC++ 2010 on Windows 7 SP1.

Please could you tell what could be the problem and how to solve it?

**Comment by olilarkin** [comment]
does setting #define PLUG_IS_INST 1 fix your problem?

**Comment by kbiakov** [comment]
Yes, it solves the problem. Thanks!
