### ISSUE TITLE
Steinberg SDK Updates

### ISSUE THREAD

**Issue by Neotriple** [olilarkin/wdl-ol#43]
Just curious (new to Github and all that). I was looking over your tutorials and noticed Steinberg's SDK does not contain 'aeffect.h' or 'aeffectx.h' anymore, however, they do include audioeffect.h and audioeffectx.h. I assume I can just rename these to the older versions and they should work. Would that be correct?

**Comment by olilarkin** [comment]
the VST3 SDK does include affect.h and affectx.h

/VST3_SDK/pluginterfaces/vst2.x/aeffectx.h
/VST3_SDK/pluginterfaces/vst2.x/aeffect.h

they are different to audioeffect.h and audioeffectx.h
