### ISSUE TITLE
cannot compile on mac 32 or 64 bits with vst sdk 3.

### ISSUE THREAD

**Issue by ad34** [olilarkin/wdl-ol#58]
I m trying to make a first plugin duplicated from IPlugEffect

When I compile it using vst sdk 3 (3.6.6) , I get the following errors

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/cssmtype.h:45:9: Unknown type name 'uint64'; did you mean 'sint64'?

I tried both 32 & 64bits, still the same error.

I m on OS X 10.11 with xcode 7.3.1

**Comment by mbrucher** [comment]
Seems to be a recurrent issue with Xcode 7.3 and after: http://forum.cockos.com/showthread.php?p=1694432

**Comment by olilarkin** [comment]
Closing because this will be fixed with new updates.
