### ISSUE TITLE
STR16 issue in IPlugVST3.cpp

### ISSUE THREAD

**Issue by josephernest** [olilarkin/wdl-ol#61]
In [this line](https://github.com/olilarkin/wdl-ol/blob/0c4ed2b854f71bdbb324feded5176ab2a57d3be6/WDL/IPlug/IPlugVST3.cpp#L200), 

```
Parameter* param = new RangeParameter( STR16(p->GetNameForHost()),
```

the macro `STR16` produces a bug, because it can't be applied this way. I see that in the last commit, this has been fixed. But I cannot use this last commit, because this breaks all compilation of my entire project, that used previous versions of `IPlugVST3.cpp`.

**How to solve just this STR16 issue without modifying anything else in `IPlugVST3.cpp`?**

**Comment by olilarkin** [comment]
Closing this issue because it was specific to a particular VSD3 STK release this will be fixed and the new version of I plug will be compatible with the latest VSD three
