### ISSUE TITLE
VST3 compilation error (error: use of undeclared identifier 'nullptr')

### ISSUE THREAD

**Issue by josephernest** [olilarkin/wdl-ol#65]
Hi,
I'm using XCode 4, Mac OS 10.5 SDK, I just duplicated IPlugEffect (`./duplicate.py IPlugEffect ABC ABC`), opened the project with XCode to select VST2 and VST3 only.
Note: I copied the right files in `/wdl-ol/VST3_SDK/...`.

Here is the error that I get:

```

In file included from /Users/User/wdl-ol/VST3_SDK/base/mac/../source/classfactory.cpp:35:
../../base/source/classfactory.h:114:2: error: use of undeclared identifier 'nullptr'
        SINGLETON (ClassFactory)
        ^
../../base/source/fobject.h:324:37: note: expanded from macro 'SINGLETON'
                static Steinberg::FObject* inst = nullptr; \
                                                  ^

The following build commands failed:
	CompileC "build/base.build/Release/base_32&64_intel.build/Objects-normal/x86_64/classfactory.o" ../source/classfactory.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
```

It seems that `nullptr` comes in C++11 which is not enabled. It seems that it cannot be enabled because it would break 10.5 target.

I'm using the default settings from wdl-ol:

    COMPILER = com.apple.compilers.llvm.clang.1_0 // or this with xcode4+/10.7+

**Do you have the same error? How do you solve this?**

**Comment by mbrucher** [comment]
I don't think you can expect any up to date library not to move to C++11 at some point. If you require support for 10.5 SDK, perhaps you should use an older version of wdlol, just like you are using an old compiler?

**Comment by josephernest** [comment]
@mbrucher The fact is that the [default common.xcconfig](https://github.com/olilarkin/wdl-ol/blob/master/common.xcconfig#L15) does not use C+11 and does provide 10.5 support:

```
BASE_SDK = macosx10.5
//BASE_SDK = macosx10.6
//BASE_SDK = macosx10.7 // Carbon GUIs do not work fully with the 10.7 or higher sdks
//BASE_SDK = macosx10.8
//BASE_SDK = macosx10.9
//CLANG_CXX_LANGUAGE_STANDARD = c++0x
//CLANG_CXX_LIBRARY = libc++
// the minimum OS to support
DEPLOYMENT_TARGET = 10.5
```

So it seems to be like this by design by @olilarkin , so it should work with 10.5 and without C+11, don't you think so @mbrucher ?

**Comment by olilarkin** [comment]
It might be something to do with the latest VST3 SDK. vstsdk365_12_11_2015_build_67.zip  Is compiling fine here against the 10.5 SDK without C++ 11 support

**Comment by josephernest** [comment]
Thanks @olilarkin. Using this vstsdk365_12_11_2015_build_67.zip version of SDK solves the problem.
