### ISSUE TITLE
Compilation errors with Visual Studio community

### ISSUE THREAD

**Issue by Pomax** [olilarkin/wdl-ol#67]
I was looking for instructions on writing a simple VST plugin and ran across http://www.martin-finke.de/blog/tags/making_audio_plugins.html which seemed super promising, but with the current version of Microsoft Visual Studio Community ("Express" is no longer a thing MS wants you to use...) I get the following compilation error after making sure I've copied all the ASIO/VST2/VST3 files into the correct directories, and after bootstrapping a new plugin project.

```
1>------ Build started: Project: MyFirstPlugin-app, Configuration: Debug Win32 ------
1>  app_dialog.cpp
1>c:\users\mike\documents\git\projects\wdl-ol\iplugexamples\myfirstplugin\app_wrapper\app_dialog.cpp(551): error C3688: invalid literal suffix '__DATE__'; literal operator or literal operator template 'operator ""__DATE__' not found
1>c:\users\mike\documents\git\projects\wdl-ol\iplugexamples\myfirstplugin\app_wrapper\app_dialog.cpp(551): error C2660: 'sprintf': function does not take 1 arguments
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========
```

**Comment by olilarkin** [comment]
this has been fixed a while ago, sorry can't find sha right now
