### ISSUE TITLE
IPlugEffect VST3 crashes when changing gain parameter

### ISSUE THREAD

**Issue by jeichelbaum** [olilarkin/wdl-ol#69]
Pretty much does what it says in the title: Building the IPlugEffect project as 32bit VST3 and loading it into FL Studio 10 results in a freeze when changing the parameter to something other than its initial value.

Compiled it with MSVC 15 Community, not sure if that messes anything up?

**Comment by jeichelbaum** [comment]
The VST2 version of it is working perfectly fine though.

**Comment by olilarkin** [comment]
closing this because old vst3 in flstudio was buggy.
