### ISSUE TITLE
Build Error, Missing file

### ISSUE THREAD

**Issue by akrifazeer94** [olilarkin/wdl-ol#71]
Hello and thank you for sharing!

I have a problem that is very crap! I work there since yesterday but I can not solve it!
I use Visual Studio 2017. I try with Visual C ++ 2010 Express but the same problem!

Thanks for a future help!

Here are the LOGS (When I build the solution):

> 1>------ Début de la génération : Projet : base, Configuration : Debug Win32 ------
> 2>------ Début de la génération : Projet : AKFMaster-aax, Configuration : Debug Win32 ------
> 3>------ Début de la génération : Projet : AKFMaster-app, Configuration : Debug Win32 ------
> 4>------ Début de la génération : Projet : AKFMaster-vst2, Configuration : Debug Win32 ------
> 1>C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\CL.exe /c /I..\.. /ZI /nologo /W3 /WX- /Od /Oy- /D _DEBUG=1 /D DEVELOPMENT=1 /Gm- /EHsc /MTd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"Win32\Debug\objects\\" /Fd"Win32\Debug\base.pdb" /Gd /TP /analyze- /errorReport:prompt ..\source\classfactory.cpp ..\source\fatomic.cpp ..\source\fbitset.cpp ..\source\fcpu.cpp ..\source\finitializer.cpp ..\source\fmemory.cpp ..\source\fpoint.cpp ..\source\frect.cpp ..\source\fthread.cpp
> 1>classfactory.cpp
> 1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\classfactory.cpp' : No such file or directory
> 1>fatomic.cpp
> 1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fatomic.cpp' : No such file or directory
> 1>fbitset.cpp
> 1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fbitset.cpp' : No such file or directory
> 1>fcpu.cpp
> 1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fcpu.cpp' : No such file or directory
> 1>finitializer.cpp
> 1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\finitializer.cpp' : No such file or directory
> 1>fmemory.cpp
> 1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fmemory.cpp' : No such file or directory
> 1>fpoint.cpp
> 1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fpoint.cpp' : No such file or directory
> 1>frect.cpp
> 1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\frect.cpp' : No such file or directory
> 1>fthread.cpp
> 1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fthread.cpp' : No such file or directory
> 1>Génération de code en cours...
> 1>Génération du projet "base_vc10.vcxproj" terminée -- ÉCHEC.
> 5>------ Début de la génération : Projet : AKFMaster-vst3, Configuration : Debug Win32 ------
> 2>DEL /Q /F /S .\build-win\aax\bin\AKFMaster.aaxplugin\
> 2>CALL ..\..\AAX_SDK\Utilities\CreatePackage.bat build-win\aax\bin\AKFMaster.aaxplugin\Contents\Win32\ ..\..\AAX_SDK\Utilities\PlugIn.ico
> 2>
> 2>:VCEnd
> 5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe /c /I..\..\VST3_SDK /I"C:\wdl-ol\IPlugExamples\AKFMaster\\..\..\..\MyDSP\\" /I..\..\WDL /I..\..\WDL\lice /I..\..\WDL\IPlug /ZI /nologo /W3 /WX- /diagnostics:classic /Od /Oy- /D VST3_API /D _DEBUG /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _WINDLL /D _MBCS /Gm /EHsc /RTC1 /MTd /GS /arch:SSE2 /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"build-win\vst3\Win32\Debug\\" /Fd"build-win\vst3\Win32\Debug\vc141.pdb" /Gd /TP /wd4996 /wd4250 /wd4018 /wd4267 /analyze- /errorReport:prompt ..\..\WDL\IPlug\IPlugVST3.cpp AKFMaster.cpp
> 2>Le chemin d'accès spécifié est introuvable.
> 4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe /c /I"C:\wdl-ol\IPlugExamples\AKFMaster\\..\..\..\MyDSP\\" /I..\..\WDL /I..\..\WDL\lice /I..\..\WDL\IPlug /ZI /nologo /W3 /WX- /diagnostics:classic /Od /Oy- /D VST_API /D VST_FORCE_DEPRECATED /D _DEBUG /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _WINDLL /D _MBCS /Gm /EHsc /RTC1 /MTd /GS /arch:SSE2 /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"build-win\vst2\Win32\Debug\\" /Fd"build-win\vst2\Win32\Debug\vc141.pdb" /Gd /TP /wd4996 /wd4250 /wd4018 /wd4267 /analyze- /errorReport:prompt ..\..\WDL\IPlug\IPlugVST.cpp AKFMaster.cpp
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: La commande "DEL /Q /F /S .\build-win\aax\bin\AKFMaster.aaxplugin\
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: CALL ..\..\AAX_SDK\Utilities\CreatePackage.bat build-win\aax\bin\AKFMaster.aaxplugin\Contents\Win32\ ..\..\AAX_SDK\Utilities\PlugIn.ico
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: 
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd" s'est arrêtée avec le code 1.
> 2>Génération du projet "AKFMaster-aax.vcxproj" terminée -- ÉCHEC.
> 6>------ Début de la génération : Projet : AKFMaster-rtas, Configuration : Debug Win32 ------
> 4>AKFMaster.cpp
> 6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1755,5): warning : The referenced project '..\..\PT9_SDK\AlturaPorts\TDMPlugIns\PlugInLibrary\WinBuild\PlugInLib.vcxproj' does not exist.
> 3>app_dialog.cpp
> 6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe /c /I.\..\..\WDL\IPlug\RTAS /I.\ /I"C:\wdl-ol\IPlugExamples\AKFMaster\\..\..\..\MyDSP\\" /I..\..\WDL /I..\..\WDL\lice /I..\..\WDL\IPlug /Zi /nologo /W3 /WX- /diagnostics:classic /Od /Ob1 /Ot /Oy- /D RTAS_API /D _HAS_ITERATOR_DEBUGGING=0 /D _SECURE_SCL=0 /D _WINDOWS /D WIN32 /D _WIN32 /D WINDOWS_VERSION /D _LIB /D _CRT_SECURE_NO_WARNINGS /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D NDEBUG /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _WINDLL /Gm- /EHa /MT /GS /arch:SSE2 /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"C:\wdl-ol\IPlugExamples\AKFMaster\build-win\rtas\Debug\\" /Fd"C:\wdl-ol\IPlugExamples\AKFMaster\build-win\rtas\Debug\vc141.pdb" /Gd /TP /wd4996 /wd4250 /wd4018 /wd4267 /FIdigicode.h /analyze- /errorReport:prompt @..\..\WDL\IPlug\RTAS\Paths_90_SDK.txt ..\..\WDL\IPlug\Hosts.cpp ..\..\WDL\IPlug\IBitmapMonoText.cpp ..\..\WDL\IPlug\IControl.cpp ..\..\WDL\IPlug\IGraphics.cpp ..\..\WDL\IPlug\IGraphicsWin.cpp ..\..\WDL\IPlug\IParam.cpp ..\..\WDL\IPlug\IPlugBase.cpp ..\..\WDL\IPlug\IPlugRTAS.cpp ..\..\WDL\IPlug\IPlugStructs.cpp ..\..\WDL\IPlug\IPopupMenu.cpp ..\..\WDL\IPlug\Log.cpp ..\..\WDL\IPlug\RTAS\IPlugCustomUI.cpp ..\..\WDL\IPlug\RTAS\IPlugGroup.cpp ..\..\WDL\IPlug\RTAS\IPlugProcess.cpp ..\..\WDL\IPlug\RTAS\IPlugProcessAS.cpp ..\..\WDL\IPlug\RTAS\IPlugProcessRTAS.cpp ..\..\WDL\IPlug\RTAS\digicode1.cpp ..\..\WDL\IPlug\RTAS\digicode2.cpp ..\..\WDL\IPlug\RTAS\digicode3.cpp AKFMaster.cpp
> 4>c:\wdl-ol\wdl\iplug\iplugvst.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : '../../VST_SDK/aeffectx.h' : No such file or directory
> 4>IPlugVST.cpp
> 5>AKFMaster.cpp
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.h(140): error C2143: erreur de syntaxe : absence de ';' avant '<'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.h(140): error C4430: spécificateur de type manquant - int est pris en compte par défaut. Remarque : C++ ne prend pas en charge int par défaut
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.h(140): error C2238: jetons inattendus avant ';'
> 5>IPlugVST3.cpp
> 6>Hosts.cpp
> 3>c:\wdl-ol\iplugexamples\akfmaster\app_wrapper\app_dialog.cpp(551): error C3688: suffixe littéral non valide '__DATE__'; opérateur littéral ou modèle d'opérateur littéral 'operator ""__DATE__' introuvable
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IBitmapMonoText.cpp
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IControl.cpp
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 3>c:\wdl-ol\iplugexamples\akfmaster\app_wrapper\app_dialog.cpp(551): error C2660: 'sprintf' : la fonction ne prend pas 1 arguments
> 6>IGraphics.cpp
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IGraphicsWin.cpp
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IParam.cpp
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IPlugBase.cpp
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IPlugRTAS.cpp
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IPlugStructs.cpp
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IPopupMenu.cpp
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>Log.cpp
> 4>c:\wdl-ol\wdl\iplug\iplugvst.h(6): fatal error C1083: Impossible d'ouvrir le fichier include : '../../VST_SDK/aeffectx.h' : No such file or directory
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IPlugCustomUI.cpp
> 6>c:\wdl-ol\wdl\iplug\rtas\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IPlugGroup.cpp
> 6>c:\wdl-ol\wdl\iplug\rtas\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IPlugProcess.cpp
> 6>c:\wdl-ol\wdl\iplug\rtas\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IPlugProcessAS.cpp
> 6>c:\wdl-ol\wdl\iplug\rtas\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>IPlugProcessRTAS.cpp
> 4>Génération de code en cours...
> 6>c:\wdl-ol\wdl\iplug\rtas\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>digicode1.cpp
> 6>c:\wdl-ol\wdl\iplug\rtas\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>digicode2.cpp
> 3>Génération du projet "AKFMaster-app.vcxproj" terminée -- ÉCHEC.
> 6>c:\wdl-ol\wdl\iplug\rtas\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>digicode3.cpp
> 4>Génération du projet "AKFMaster-vst2.vcxproj" terminée -- ÉCHEC.
> 6>c:\wdl-ol\wdl\iplug\rtas\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>AKFMaster.cpp
> 6>C:\wdl-ol\WDL\IPlug\RTAS\digicode.h(24): fatal error C1083: Impossible d'ouvrir le fichier include : 'ForcedInclude.h' : No such file or directory
> 6>Génération de code en cours...
> 6>Génération du projet "AKFMaster-rtas.vcxproj" terminée -- ÉCHEC.
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.h(140): error C2143: erreur de syntaxe : absence de ';' avant '<'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.h(140): error C4430: spécificateur de type manquant - int est pris en compte par défaut. Remarque : C++ ne prend pas en charge int par défaut
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.h(140): error C2238: jetons inattendus avant ';'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(199): error C2065: 'Lp' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(199): error C2227: la partie gauche de '->GetNameForHost' doit pointer vers un type class/struct/union/générique
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(199): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(201): error C2065: 'Lp' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(201): error C2227: la partie gauche de '->GetLabelForHost' doit pointer vers un type class/struct/union/générique
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(201): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(207): error C2664: 'Steinberg::Vst::RangeParameter::RangeParameter(Steinberg::Vst::RangeParameter &&)' : impossible de convertir l'argument 1 de 'int' en 'const Steinberg::Vst::TChar *'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(207): note: La conversion d'un type intégral en type pointeur nécessite reinterpret_cast, un cast de style C ou un cast de style fonction
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(217): error C2065: 'Lp' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(217): error C2227: la partie gauche de '->GetNameForHost' doit pointer vers un type class/struct/union/générique
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(217): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(219): error C2065: 'Lp' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(219): error C2227: la partie gauche de '->GetLabelForHost' doit pointer vers un type class/struct/union/générique
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(219): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(221): error C2664: 'Steinberg::Vst::StringListParameter::StringListParameter(const Steinberg::Vst::StringListParameter &)' : impossible de convertir l'argument 1 de 'int' en 'const Steinberg::Vst::TChar *'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(221): note: La conversion d'un type intégral en type pointeur nécessite reinterpret_cast, un cast de style C ou un cast de style fonction
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(229): error C2065: 'Lp' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(229): error C2227: la partie gauche de '->GetDisplayText' doit pointer vers un type class/struct/union/générique
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(229): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(250): error C2065: 'viewsArray' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(250): error C2228: la partie gauche de '.removeAll' doit avoir un class/struct/union
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(250): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(277): error C2039: 'remove' : n'est pas membre de 'Steinberg::Vst::BusList'
> 5>c:\wdl-ol\vst3_sdk\public.sdk\source\vst\vstbus.h(141): note: voir la déclaration de 'Steinberg::Vst::BusList'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(286): error C2039: 'remove' : n'est pas membre de 'Steinberg::Vst::BusList'
> 5>c:\wdl-ol\vst3_sdk\public.sdk\source\vst\vstbus.h(141): note: voir la déclaration de 'Steinberg::Vst::BusList'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(303): error C2039: 'remove' : n'est pas membre de 'Steinberg::Vst::BusList'
> 5>c:\wdl-ol\vst3_sdk\public.sdk\source\vst\vstbus.h(141): note: voir la déclaration de 'Steinberg::Vst::BusList'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(761): error C2065: 'viewsArray' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(761): error C2228: la partie gauche de '.add' doit avoir un class/struct/union
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(761): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(766): error C2065: 'viewsArray' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(766): error C2228: la partie gauche de '.total' doit avoir un class/struct/union
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(766): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(768): error C2065: 'viewsArray' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(768): error C2228: la partie gauche de '.at' doit avoir un class/struct/union
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(768): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(770): error C2065: 'viewsArray' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(770): error C2228: la partie gauche de '.removeAt' doit avoir un class/struct/union
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(770): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(962): error C2065: 'viewsArray' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(962): error C2228: la partie gauche de '.at' doit avoir un class/struct/union
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(962): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(962): error C2227: la partie gauche de '->resize' doit pointer vers un type class/struct/union/générique
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(976): error C2065: 'viewsArray' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(976): error C2228: la partie gauche de '.at' doit avoir un class/struct/union
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(976): note: le type est 'unknown-type'
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(986): error C2065: 'viewsArray' : identificateur non déclaré
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(986): error C2228: la partie gauche de '.at' doit avoir un class/struct/union
> 5>c:\wdl-ol\wdl\iplug\iplugvst3.cpp(986): note: le type est 'unknown-type'
> 5>Génération de code en cours...
> 5>Génération du projet "AKFMaster-vst3.vcxproj" terminée -- ÉCHEC.
> ========== Génération : 0 a réussi, 6 a échoué, 2 mis à jour, 0 a été ignoré ==========

**Comment by DropSnorz** [comment]
I can't really help you since i don't know your project strucutre and i'm not an expert with visual studio traces. But if i understand right your project is in _C:\wdl-ol\IPlugExamples_, like all other examples. Have you tried to build IPlugEffect example ? 

- 1>There seems that there is troubles with your VST3 SDK. Check if related missing files are in wdl-ol/VST3_SDK
- 4> Same things with VST_SDK folder. You must have "aeffect.h" and "aeffectx.h" inside.

Check this great post about how to setup your project. http://www.martin-finke.de/blog/articles/audio-plugins-002-setting-up-wdl-ol/

**Comment by akrifazeer94** [comment]
605/5000
Hello and thank you for answering!

So yes I am with IPlugEffect as in the example. I saw that "aeffect.h" and "aeffectx.h" was missing and I had set its after, but the error came from VST 2 and 3 and it showed me a lot of missing file that I didn ' Is not able to locate even on the internet. That's why I came to you. I followed these instructions to the letter (configuration ...) but bad result.

Almost all the files of "../source/" are not available and I have not found it !!

Here are all the files I missed lately.

```
1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\classfactory.cpp' : No such file or directory
1>fatomic.cpp
1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fatomic.cpp' : No such file or directory
1>fbitset.cpp
1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fbitset.cpp' : No such file or directory
1>fcpu.cpp
1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fcpu.cpp' : No such file or directory
1>finitializer.cpp
1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\finitializer.cpp' : No such file or directory
1>fmemory.cpp
1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fmemory.cpp' : No such file or directory
1>fpoint.cpp
1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fpoint.cpp' : No such file or directory
1>frect.cpp
1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\frect.cpp' : No such file or directory
1>fthread.cpp
1>c1xx : fatal error C1083: Impossible d'ouvrir le fichier source : '..\source\fthread.cpp' : No such file or directory
```

Thank you !

**Comment by DropSnorz** [comment]
Ok you're right. I just found the missing files in _3.6.5_ but they are not included in _3.6.7_ release.
You can download the archive here: http://www.steinberg.net/sdk_downloads/vstsdk365_12_11_2015_build_67.zip

**Comment by akrifazeer94** [comment]
Cool thank you !! I'll be able to start! Thanks again !

**Comment by akrifazeer94** [comment]
Tu est français ?

**Comment by DropSnorz** [comment]
Oui.  Mon piètre anglais m'aurait t-il trahi ? ^^

**Comment by DropSnorz** [comment]
Donc tu sais où me trouver si tu as besoin d'un coup de main avec ton plugin. 
Si ton problème est résolu je t'invite à fermer l'issue.

**Comment by akrifazeer94** [comment]
Oui merci l'a ça fonctionne bien ! Ok pas de soucis !
