### ISSUE TITLE
Cant build VST3 using VST3 SDK (3.6.8)

### ISSUE THREAD

**Issue by skogssnoddas** [olilarkin/wdl-ol#76]
Hi,
Trying to build VST3 using WDL-OL IplugExamples, I get quite a few errors, for example:
"Error	C1083	Cannot open source file: '..wdl-ol\VST3SDK\base\source\classfactory.cpp': No such file or directory"
I'm using SDK 3.6.8, VS++ 2015 Community, win10 64
and following martin finkes tutorial: [making_audio_plugins](http://www.martin-finke.de/blog/tags/making_audio_plugins.html
)

**Comment by olilarkin** [comment]
give me a break it only came out today!

**Comment by olilarkin** [comment]
I will look into it for my forthcoming update

**Comment by skogssnoddas** [comment]
Sorry, I'm new to this and cant get hold of the old SDK... Is the new SDK not compatible with wdk-ol?

**Comment by skogssnoddas** [comment]
*l

**Comment by olilarkin** [comment]
not yet

**Comment by skogssnoddas** [comment]
OK, good to know, I'll focus on vst2 for now :) Thank you for all your amazing work!

**Comment by olilarkin** [comment]
Old Vst3 here http://www.steinberg.net/sdk_downloads/vstsdk365_12_11_2015_build_67.zip

**Comment by skogssnoddas** [comment]
Thanks for the link!

**Comment by emilm** [comment]
I ran into this issue as well. Is there a lot to change?
